### ISSUE TITLE
Content aware dynamic height. 

### ISSUE THREAD

**Issue by Wiblz** [jonasgeiler/svelte-tiny-virtual-list#17]
I'm having a difficult time making dynamic heights work. I am writing a basic chat window with messages of different heights (depending on amount of text inside. Currently I am trying to solve it by binding `offsetHeight` of the message to `itemSize` but it causes a lot of jumping and flickering with constant rerendering of components. It is obvious that I am doing something wrong and I would really appreciate any hints on what is wrong or what is the right way of doing it. 

Here's REPL link to my code: https://svelte.dev/repl/6a5c26b0b7fa4351a9d30f3f907e00cf?version=3.48.0

**Comment by skayo** [comment]
Any updates on this?
Let me know if you need any help!

**Comment by jonasgeiler** [comment]
Closing this now due to inactivity. Let me know if you need additional help.
