### ISSUE TITLE
Sveltekit v2 error

### ISSUE THREAD

**Issue by eranmiller** [jonasgeiler/svelte-tiny-virtual-list#32]
Happy belated New Year.

**[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.
svelte-tiny-virtual-list@2.0.5**

With all the changes coming to Svelte 5 and the strong recommendation to upgrade to Sveltekit 2 would you suggest using an alternate component, or do you plan to update the code?

I hope you do, and I thank you for creating such a useful component.

**Comment by jonasgeiler** [comment]
Hey Eran!
I just started working on a new version using the SvelteKit library template over in the `feat/sveltekit` branch. Will release a `3.0.0-alpha.0` version at some point in the (hopefully) near future, and after confirming everything still works I will move into beta and maybe let some users test it, and after that I will release `3.0.0` 😊 

So proper SvelteKit support is coming soon!

**Comment by jonasgeiler** [comment]
Should be fixed by #42. Release coming soon!
