### ISSUE TITLE
ScrollOffset doesnt set scroll position of wrapper on initial render

### ISSUE THREAD

**Issue by tarb** [jonasgeiler/svelte-tiny-virtual-list#4]
I cant get the List to render at a certain scroll offset on first render, if the scrollOffset props changes subsequent renders are positioned correctly, but on initial render the wrapper is always positioned at the top. The correct virtual items are rendered (sometimes out of view if the offset is higher enough) and they can be seen in the devtools as being in the right spot.

**Comment by Skayo** [comment]
If this issue is still relevant: Could you provide me an example code on [Svelte REPL](https://svelte.dev/repl)?
Would help a lot!

**Comment by skayo** [comment]
Any updates on this? I'd like to close this issue

**Comment by jonasgeiler** [comment]
Closing this now due to inactivity. If the problem persists after I release `3.0.0`, please let me know!
