### ISSUE TITLE
issue in edge webview

### ISSUE THREAD

**Issue by anvlkv** [jonasgeiler/svelte-tiny-virtual-list#63]
I have an issue in webview on windows, the scroll list appears horizontal but it has the necessary properties

![image](https://github.com/jonasgeiler/svelte-tiny-virtual-list/assets/2813794/547c885d-77b3-4900-86fe-c47e1529f130)

After I toggle `flex-direction` property off and on again it looks correct but scrolling doesn't bring up new items

![image](https://github.com/jonasgeiler/svelte-tiny-virtual-list/assets/2813794/f7e159a6-62d9-40e8-b27a-d7f203d56f1b)

My usage can be seen here https://github.com/anvlkv/text-tut-ryadom/blob/fix/windows-improvements/src/lib/taskList.svelte#L54

**Comment by jonasgeiler** [comment]
Sorry how late I am to this but unfortunately, I'm not able to reproduce this issue 🤔 I even downloaded your repository and ran the app myself, but the list seems totally fine. Is there any way you would be able to reproduce this using https://svelte.dev/repl ?

**Comment by anvlkv** [comment]
Thanks for getting back to my issue and trying it. I probably won't get to it any soon. May have to do with windows/egde version as well. I close this one and if the issue remains on new versions I'll try to make a reproduction.
